### ISSUE TITLE
Server freezes during temp cal

### ISSUE THREAD

**Issue by brandogw** [FYNCH-BIO/evolver#28]
During temperature calibration, during updating the temperature, the server freezes up. This is the output log from the server.

`Output to arduino:
xrNaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN, !
Received from arduino:
temp2018,1980,1986,1997,1983,1961,1973,1972,1986,1954,1919,1956,1994,1957,1943,1969,end
Output to arduino:
we4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095, !
Received COMMAND
Output to arduino:
xr1517,1478,1484,1492,1481,1461,1472,1470,1485,1454,1419,1456,1492,1458,1442,1467, !
Error in running commands - relinquishing serial
an integer is required (got type NoneType)
Got command from BROADCAST
Output to arduino:
we4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095, !
Error in running commands - relinquishing serial
'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
Got command from BROADCAST
`

**Comment by brandogw** [comment]
Temperatures still update but the broadcast just isnt working.

**Comment by zheins** [comment]
Resolved by #32
